## Heatmaps
# This is a script for understanding the summary csv generated by the model tuning stage


data <- dataFULL
data <- dataFULL %>% filter(numBehaviours == 4)
  
var1 <- summarisedModelOptions$window_length
var2 <- summarisedModelOptions$ntree
heat <- summarisedModelOptions$General_accuracy
data <- summarisedModelOptions

generate_heatmap <-  function(data, heat, var1, var2){

  map_2d <- ggplot(data, aes(x = var1, y= var2, fill = heat))+
    geom_tile() +
    theme_minimal() +
    theme(legend.position = "right",
          axis.text.x = element_text(angle = 45, hjust = 1),
          panel.grid = element_blank(),
          panel.border = element_rect(color = "black", fill = NA, linewidth = 1)) +
    scale_fill_gradientn(colors = c("#357ABD", "#D9534F", "#FFD966"), na.value = "transparent")
  
  
  map_2d
  
  
}

# Create a formula with all possible interactions between the variables
formula <- as.formula("General_accuracy ~ (DesiredHz + numBehaviours + Balancing + NumFeatures + OverlapPercent + WindowLength + ntree)^2")

# Fit the GLM
lm_model <- lm(formula, data = data)

# Print the summary of the model
summary(lm_model)